title: Olajide Ojo – QA Engineer Portfolio
description: Senior QA Engineer skilled in Appium, Cypress, Postman, JMeter, and more.
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
